### ISSUE TITLE
ImportError: No module named csimdjson

### ISSUE THREAD

**Issue by VoidBird** [TkTech/pysimdjson#18]
I use command `sudo CFLAGS="-march=native -std=c++17" python setup.py install`  to install。After it success, I use `import simdjson` in my python2.7 interpreter, then I got this error:
```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import simdjson
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "simdjson/__init__.py", line 1, in <module>
    from simdjson.csimdjson import (
ImportError: No module named csimdjson
```

**Comment by TkTech** [comment]
Can you post the output of your setup.py install?
