### ISSUE TITLE
Out of bounds access when using parser.parse on 0-length memory view in 4.0.0

### ISSUE THREAD

**Issue by chutz** [TkTech/pysimdjson#81]
This code will result in an out of bounds memory access exception:
```python
import simdjson

simdjson.Parser().parse(memoryview(b""))
```
The output is
```text
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    simdjson.Parser().parse(memoryview(b""))
  File "simdjson/csimdjson.pyx", line 484, in csimdjson.Parser.parse
IndexError: Out of bounds on buffer access (axis 0)
```

It should raise a ValueError complaining that no JSON was found rather than an index error, as an empty bytes does.

**Comment by TkTech** [comment]
Thanks! This will go out as 4.0.1 once the tests and release pass.
